version: '3.4'

services:

  scat-pos:
    build: .
    links:
      - db
      - search
    env_file:
      - sample.env
    working_dir: /app/app
    command: [ php, "-S", "0.0.0.0:5080", "pos.php" ]
    ports:
      - 5080:5080
    volumes:
#      - .:/app
      - ./config/php-fpm-extra.conf:/usr/local/etc/php-fpm.d/php-fpm-extra.conf
    restart: always

  db:
    image: mysql:8.0.32
    env_file:
      - sample.env
    # old password auth so sphinx can access it
    command: [ mysqld, --local-infile=1, --default_authentication_plugin=mysql_native_password ]
    expose:
      - "3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - data:/var/lib/mysql
    restart: always

  search:
    image: macbre/sphinxsearch:3.4.1
    links:
      - db
    expose:
      - "9306"
    env_file:
      - sample.env
    volumes:
      - ./config/search:/opt/sphinx/conf
      - searchdata:/var/data
    restart: always

volumes:
  data:
  searchdata:
